### ISSUE TITLE
bcbio build fails - TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by kern3020** [chapmanb/cloudbiolinux#195]
Hello, 

While trying to install bcbio, I typed...

```
$  python bcbio_nextgen_install.py /opt/bcbio/share/bcbio --tooldir=/opt/bcbio   --genomes hg19 --genomes GRCh37  --aligners bwa
```
It failed. 
```
  File "/opt/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/package/__init__.py", line 68, in _get_sh
ell_exports
    % (env.system_install, env.system_install))}
TypeError: not all arguments converted during string formatting
```

The error seems straightforward. There are two arguments(elements in the tuple) and one position (%s). 

```
  return {"path": "export PATH=%s:$PATH" % bin_dir,
            "ld_library": "export LD_LIBRARY_PATH=%s:$LD_LIBRARY_PATH" % ldlib_path,
            "perl": ("export PERL5LIB=%s/lib/perl5:${PERL5LIB}"
                     % (env.system_install, env.system_install))}
```

Unfortunately, when I update the code on my machine, it seems to refresh it from the main repository. 

-jk

**Comment by chapmanb** [comment]
John -- sorry about my mistake. I pushed a fix to resolve this so if you re-run it should build cleanly.

For future issues, if you create a tmpbcbio-install and symlink a locally fixed `cloudbiolinux` into it bcbio will use that instead of downloading a new version from GitHub. This is a way to test or work around issues. Thanks again for the heads up on the problem.
