### ISSUE TITLE
$VERSION in vagrant section

### ISSUE THREAD

**Issue by dakl** [chapmanb/cloudbiolinux#200]
Hi, 

In the README file, what should the variable `$VERSION` be set to in the section describing use with Vagrant? Without example/s or current version, it's a bit hard to figure out and get working (I coundn't). 

thanks

**Comment by chapmanb** [comment]
Apologies about the confusing documentation. We experimented with making Vagrant images available for a while but it didn't up being very successful due to large download sizes, so no longer do this. We've been focusing on Docker recently to avoid some of the issues, and have downloads available for it:

https://github.com/chapmanb/cloudbiolinux#docker

You can still use CloudBioLinux to build Vagrant/Virtualbox images from scratch if you prefer to use that.

Sorry again for the confusion and hope this helps.
