### ISSUE TITLE
Problem downloading the biological data

### ISSUE THREAD

**Issue by joemphilips** [chapmanb/cloudbiolinux#206]
Hi, I'm a bioinformatician working in Japan.
I tried to install Biological data on my local biolinux8 (not cloudbiolinux) 
by typing the command as follows
`fab -f fabfile.py -H localhost install_data_s3`
I successfully installed an transcriptome data of all species. But after that, when it tries to
`wget https://s3.amazonaws.com/biodata/genomes/phix-bowtie2.tar.xz`
It fails and stops provisioning.
I thought this might be an problem caused by discordance between config/biodata.yaml and actual amazon S3 bucket since when I tried to access amazon S3 bucket by my browser, it shows an following error.

```xml
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>genomes/phix-bowtie2.tar.xz</Key>
<RequestId>529B3AECB4B5DD65</RequestId>
<HostId>
4n9ZcLEN/lN9rxgQdvYsCaF0b+3khrK2tC9cUGhY0Qx23IYtSzHaH8zyosCo/EpV
</HostId>
</Error>
```

Is there somoething wrong with Amazon S3 bucket Biological data? Or am I making something wrong?
Thanks for reply in advance.

**Comment by joemphilips** [comment]
I found that probably this is a problem of proxy server of my institute.
we are not able to download by https protocol without SSL certificate so
`wget --no-check-certificate  https://s3.amazonaws.com/biodata/genomes/phix-bowtie2.tar.xz` fails.
I asked to my institute's security team to change the policy but they denied. :cry: 

Is it able to change the amazon S3 bucket configuration to use SSL ?

**Comment by chapmanb** [comment]
Sorry about the issue. We don't have pre-built S3 indexes for all genomes, so this particular download fails due to not have pre-prepared indices for phiX. Some genomes don't make sense to maintain since they're quick to build locally. You can install with:
```
fab -f fabfile.py -H localhost install_data
```
which will try S3, then GGD recipes (https://github.com/arq5x/ggd), then fall back to building locally. Hopefully this will get the indices installed for you. Please let us know if you have any other problems and happy to re-open and discuss more.
