### ISSUE TITLE
Variation reference data

### ISSUE THREAD

**Issue by vladsaveliev** [chapmanb/cloudbiolinux#223]
Hi Brad,

I got a few questions regarding the recipes.
1. I'm wondering why dbSNP is downloaded from the archive subfolder (ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606_b147_GRCh38p2/VCF/archive/All_20160407.vcf.gz), instead of the latest (ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606_b147_GRCh38p2/VCF/All_20160527.vcf.gz)?
2. dbSNP for hg19 (unlike for hg38) is downloaded from another source, and is very outdated - v138 vs. v147. Any specific reason for keeping it that?
3. There is no recipe at all for COSMIC for hg38.
4. ClinVar for hg38 is downloaded from archive and very outdated ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh38/archive/2015, but it should always correspond to the used version of dbSNP in order to make annotations consistent. 
5. And for hg19, there is not ClinVar recipe at all.

If you have no objections, I can fix and update all human recipes and make a pull request. I also added recipes for refGene files (http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/refGene.txt.gz) that I would like to use for BED annotation for Seq2C (and hopefully for other purposes), let me know if that's a correct way to do it or I should fix something, and if it is okay with out at all: https://github.com/vladsaveliev/cloudbiolinux/commit/9da6bc73a10de34de34b3a31b8917b7247c8b0f7

**Comment by vladsaveliev** [comment]
There is a problem with COSMIC that it's actually proprietary, thus cloudbiolinux can't seem to be able to provide the latest version. I'm wondering what is the most organic way to support setting of a custom COSMIC location, so it works smoothly with bcbio automated installation.

**Comment by chapmanb** [comment]
Vlad -- thanks so much. I'll leave specific comments in your PR but to answer the general questions you haven't already:

1. We download from the subfolder because the latest URL is not stable and will become invalid when they do an update. To avoid breaking builds we use older stable URLs and can update those as needed.
2. We just kept dbSNP at the version used in the Broad bundle but I'm agnostic about this and happy to update to the latest.

Thanks again, I'll provide other comments in #224
