### ISSUE TITLE
hisat2 indexes unavailable on s3

### ISSUE THREAD

**Issue by cbrueffer** [chapmanb/cloudbiolinux#226]
There are no hisat2 indexes available on s3 (at least for GRCh37, hg38 and hg38-noalt):

[localhost] local: wget --continue --no-check-certificate -O hg38-hisat2.tar.xz 'https://s3.amazonaws.com/biodata/genomes/hg38-hisat2.tar.xz'
--2016-08-09 21:35:50--  https://s3.amazonaws.com/biodata/genomes/hg38-hisat2.tar.xz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.80.67
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.80.67|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-08-09 21:35:50 ERROR 404: Not Found.

**Comment by chapmanb** [comment]
Christian -- thanks for the work on hisat2 and the discussion thread. We should be installing these via the new GGD recipe approach now instead of this older approach (which often fails since we don't provide pre-computed indexes for everything; then we fall back to GGD or local indexing). Ideally we'll move everything to GGD recipes but haven't done so yet. @roryk what do you think the best way to handle hisat2 for non-hg38 is?

**Comment by roryk** [comment]
Hi everyone,

+1, thanks for the cleanups Christian. My original plan was to not support hisat2 for genomes that don't have alts yet, since bwa and STAR are pretty good options for aligning/split-read aligning respectively, but if there are good reasons for not running hisat2 over STAR for split-read aligning I'm up for adding support for them in.

**Comment by cbrueffer** [comment]
BTW, there are no STAR indexes for GRCh37, hg38 or hg38-noalt either (GGD or S3). Maybe worth adding them?

**Comment by roryk** [comment]
Hi Christian,

The STAR indexes are huuuuge so we just build them locally rather than put them up for download.

**Comment by cbrueffer** [comment]
Ah, makes sense. Good to know :-)

**Comment by naumenko-sa** [comment]
https://github.com/chapmanb/cloudbiolinux/blob/master/ggd-recipes/hg38/hisat2.yaml
