### ISSUE TITLE
Failed to install due to broken link

### ISSUE THREAD

**Issue by BoPeng** [chapmanb/cloudbiolinux#290]
piR_hg19_v1.0.bed.gz in [mirbase.yaml](https://github.com/chapmanb/cloudbiolinux/blob/adeaa4d2d410fb183f90459d63a0c17a069569a4/ggd-recipes/hg19/mirbase.yaml#L23) no longer available due to broken link `http://www.regulatoryrna.org/database/piRNA/download/archive/v1.0/bed/piR_hg19_v1.0.bed.gz`

This caused bcbio-nextgen to fail (https://github.com/bcbio/bcbio-nextgen/issues/2726).

**Comment by lpantano** [comment]
Hi, 

we are aware of this, I will fix this tomorrow.

I think you can go into the recipe and comment that line and restart installation.

Sorry about the issue.

Cheers

sent not from my computer

**Comment by lpantano** [comment]
This should be fixed now for all the human genome versions.

Thanks

**Comment by naumenko-sa** [comment]
Hi Lorena @lpantano!

I have a related question: you suggested to edit a recipe and finish the installation.
But if you are running bcbio upgrade [something], it downloads cloudbiolinux from github master repo, which has the original recipe.  How you would resume bcbio installation if it failed, you fixed the recipe in the genome/.../where  install happens/txtmp? I assume just running ggd-run.sh or how I described it here https://github.com/chapmanb/cloudbiolinux/blob/master/doc/hacking.md#testing-a-ggd-recipe won't help, because after installation bcbio is also updating its config files outside of cloudbiolinux. 

My current algorithm is:
1. bcbio update fails
2. I fix the recipe in my branch of cloudbiolinux, test it locally.
3. I do a pull request.
4. Request is accepted.
5. I do installation again.

Thanks!
Sergey

**Comment by lpantano** [comment]
Rory added some tips here:
https://github.com/hbc/knowledgebase/blob/master/computing/bcbio/bcbio_genomes.md

The idea is to create this before re-start the installation:

  mkdir tmpbcbio-install
  ln -s $COPYWITHPATCH/cloudbiolinux tmpbcbio-install/cloudbiolinux
  bcbio_nextgen.py upgrade….


I don’t know if that answer the question here, but it is how I get the
local patches into bcbio.

-- 
Lorena Pantano, P.h.D
Research Scientist
Biostatistics Department
Harvard T.H. Chan School of Public Health
https://mirtop.github.io <https://mirtop.github.io/>
https://lpantano.github.io

On April 25, 2019 at 2:32:52 PM, Sergey Naumenko (notifications@github.com)
wrote:

Hi Lorena @lpantano <https://github.com/lpantano>!

I have a related question: you suggested to edit a recipe and finish the
installation.
But if you are running bcbio upgrade [something], it downloads
cloudbiolinux from github master repo, which has the original recipe. How
you would resume bcbio installation if it failed, you fixed the recipe in
the genome/.../where install happens/txtmp? I assume just running
ggd-run.sh or how I described it here
https://github.com/chapmanb/cloudbiolinux/blob/master/doc/hacking.md#testing-a-ggd-recipe
won't help, because after installation bcbio is also updating its config
files outside of cloudbiolinux.

My current algorithm is:

   1. bcbio update fails
   2. I fix the recipe in my branch of cloudbiolinux, test it locally.
   3. I do a pull request.
   4. Request is accepted.
   5. I do installation again.

Thanks!
Sergey

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/chapmanb/cloudbiolinux/issues/290#issuecomment-486788584>,
or mute the thread

**Comment by naumenko-sa** [comment]
Thanks, Lorena! I see, so if bcbio sees cloudbiolinux folder it does not re-upload it. It is helpful. S
